name: 4s

windows:
  - styles:
      layout: ea7f,192x54,0,0{134x54,0,0,0,57x54,135,0,1}
      root: ~/Development/@4site/4s/4s-site/wp-content/themes/foursite/blocks/styles

      panes:
        - vim
        - npm run dev

  - theme:
      root: ~/Development/@4site/4s/4s-site/wp-content/themes/foursite

      panes:
        - vim

  - root:
      root: ~/Development/@4site/4s/4s-site

      panes:
        - 

  - debug:
      root: ~/Development/@4site/4s/4s-site

      panes:
        - tail -f wp-content/debug.log
