name: clk

windows:
  - styles:
      root: ~/Development/@4site/clk/clk-site/wp-content/themes/clk/resources/assets

      panes:
        - vim

  - theme:
      root: ~/Development/@4site/clk/clk-site/wp-content/themes/clk

      panes:
        - vim

  - build:
      root: ~/Development/@4site/clk/clk-site/wp-content/themes/clk

      panes:
        - nvm use 10 && npm start

  - root:
      root: ~/Development/@4site/clk/clk-site

      panes:
        - 
