name: fpf

windows:
  - theme:
      root: ~/Development/@4site/fpf/fpf-site/wp-content/themes/fpf

      panes:
        - vim

  - root:
      root: ~/Development/@4site/fpf/fpf-site

      panes:
        - 
