name: fwa

windows:
  - plugin:
      layout: ea7f,192x54,0,0{134x54,0,0,0,57x54,135,0,1}
      root: ~/Development/@4site/fw/fwa-site/wp-content/plugins/fwa-mobilize-events

      panes:
        - vim
        - 

  - theme:
      layout: ea7f,192x54,0,0{134x54,0,0,0,57x54,135,0,1}
      root: ~/Development/@4site/fw/fwa-site/wp-content/themes/fww-theme-twentytwenty-child

      panes:
        - vim
        - 

  - root:
      layout: ea7f,192x54,0,0{134x54,0,0,0,57x54,135,0,1}
      root: ~/Development/@4site/fw/fwa-site

      panes:
        - vim
        - 
