name: fwme

windows:
  - styles:
      layout: ea7f,192x54,0,0{134x54,0,0,0,57x54,135,0,1}
      root: ~/Development/@4site/fw/fw-mobilize-events/modules/page/assets/styles

      panes:
        - vim
        - npm run dev

  - plugin:
      root: ~/Development/@4site/fw/fw-mobilize-events

      panes:
        - vim

  - site:
      root: ~/Development/@4site/fw/fww-site

      panes:
        - 

  - site:logs:
      layout: even-horizontal
      root: ~/Development/@4site/fw/fww-site

      panes:
        - tail -f wp-content/debug.log
        - tail -f wp-content/uploads/fw-mobilize-events/fw-mobilize-events.log
