name: ng
root: ~/Development/@4site/ng

windows:
  - engrid-scripts:
      root: ~/Development/@4site/ng/engrid-scripts
      layout: 0901,190x51,0,0{124x51,0,0,27,65x51,125,0[65x26,125,0,28,65x24,125,27,29]}

      panes:
        - vim
        - cd packages/common; npm run watch
        - cd ../engrid-oc; npm run watch:common

  - root:
      layout: even-horizontal
      panes:
        - cd engrid-scripts
        - cd engrid-oc
