name: oc
root: ~/Development/@4site/oc/app/public/wp-content/themes/oco-wp

windows:
  - theme:
      root: ~/Development/@4site/oc/app/public/wp-content/themes/oco-wp/sass

      panes:
        - vim

  - theme.build:
      root: ~/Development/@4site/oc/app/public/wp-content/themes/oco-wp

      panes:
        - nvm use 10 && gulp

  - root:
      root: ~/Development/@4site/oc/app/public

      panes:
        - 
