name: oc

windows:
  - styles:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp/sass/4site

      panes:
        - vim

  - templates:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

      panes:
        - vim

  - build:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

      panes:
        - npm run watch

  - root:
      root: ~/Development/@4site/oc/oc-site

      panes:
        - 
