name: oc
root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

windows:
  - v4:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp/oc-blocks

      panes:
        - vim

  - legacy:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

      panes:
        - vim

  - legacy:build:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

      panes:
        - npm run watch

  - root:
      root: ~/Development/@4site/oc/oc-site

      panes:
        - 
