name: oc
root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

windows:
  - v4:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp/oc-blocks

      panes:
        - vim

  - theme:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

      panes:
        - vim

  - root:
      root: ~/Development/@4site/oc/oc-site

      panes:
        - 

  - debug:
      root: ~/Development/@4site/oc/oc-site/wp-content

      panes:
        - tail -f debug.log

  - theme:build:
      root: ~/Development/@4site/oc/oc-site/wp-content/themes/oco-wp

      panes:
        - npm run watch
