name: oc-library
root: ~/Development/@4site/oc/oc-library

windows:
  - modules:
      root: ~/Development/@4site/oc/oc-library/modules

      panes:
        - vim

  - root:
      root: ~/Development/@4site/oc/oc-library

      panes:
        - 

  - build:
      root: ~/Development/@4site/oc/oc-library
      layout: 4c84,148x45,0,0{96x45,0,0,8,51x45,97,0,24}

      panes:
        - npm run dev
