name: on

windows:
  - theme:
      root: ~/Development/@4site/on/on-site/wp-content/themes/oneill

      panes:
        - vim

  - root:
      root: ~/Development/@4site/on/on-site

      panes:
        - 
