name: pr

windows:
  - extension:
      root: ~/Development/@adaptably/raycast/productive

      panes:
        - vim

  - build:
      root: ~/Development/@adaptably/raycast/productive

      panes:
        - npm run dev
