name: prototype
root: <%= Dir.pwd %>

windows:
  - ui:
      layout: 3ec9,144x45,0,0{94x45,0,0,0,49x45,95,0[49x35,95,0,3,49x9,95,36,4]}
      root: <%= Dir.pwd %>/ui

      panes:
        - vim
        - npm run develop
        - 

  - api:
      layout: 3ec9,144x45,0,0{94x45,0,0,0,49x45,95,0[49x35,95,0,3,49x9,95,36,4]}
      root: <%= Dir.pwd %>/api

      panes:
        - vim
        - npm run develop
        - 

  - root:
      panes:
        - 
