name: rlc-website

windows:
  - server:
      root: ~/Development/@rlc/website
      layout: da6b,152x40,0,0[152x32,0,0,1,152x7,0,33{28x7,0,33,4,123x7,29,33,5}]

      panes:
        - ta && be rails s
        - local-ssl-proxy --source 3010 --target 3000 --cert ./.ssh/localhost.pem --key ./.ssh/localhost-key.pem
        - be sidekiq

  - code:
      root: ~/Development/@rlc/website

      panes:
        - vim

  - root:
      root: ~/Development/@rlc/website

      panes:
        -
