name: st

windows:
  - ui:
      root: ~/Development/@4site/st/sharethumb-frontend

      panes:
        - vim

  - ui:server:
      root: ~/Development/@4site/st/sharethumb-frontend

      panes:
        - npm run dev

  - api:
      root: ~/Development/@4site/st/sharethumb

      panes:
        - vim

  - api:server:
      root: ~/Development/@4site/st/sharethumb
      layout: even-horizontal

      panes:
        - npm run api:start:dev
        - npm run bot:start:dev
