name: tc
root: ~/Development/@4site/tidycontact

windows:
  - e2e:
      root: ~/Development/@4site/tidycontact/e2e

      panes:
        - vim

  - email.api:
      root: ~/Development/@4site/tidycontact/apps/email/api

      panes:
        - vim

  - email.batch.ui:
      root: ~/Development/@4site/tidycontact/apps/email/batch.ui

      panes:
        - vim

  - standalone.ui:
      root: ~/Development/@4site/tidycontact/apps/standalone.ui

      panes:
        - vim

  - database:
      root: ~/Development/@4site/tidycontact/packages/database

      panes:
        - vim

  - root:
      panes:
        - 
