name: wfs

windows:
  - e2e:
      root: ~/Development/@jrh/cms-workflow/e2e

      panes:
        - vim

  - ui:
      root: ~/Development/@jrh/cms-workflow/ui

      panes:
        - vim

  - ui:servers:
      root: ~/Development/@jrh/cms-workflow/ui
      layout: even-horizontal

      panes:
        - npm run serve:ui:dev
        - npm run serve:storybook:dev

  - cms:
      root: ~/Development/@jrh/cms-workflow/cms

      panes:
        - vim

  - cms:server:
      root: ~/Development/@jrh/cms-workflow/cms

      panes:
        - npm run serve:strapi:dev

  - root:
      root: ~/Development/@jrh/cms-workflow

      panes:
        - 
