name: wpf

windows:
  - library:
      root: ~/Development/@adaptably/wp-foundation-library/
      panes:
        - vim

  - theme:
      root: ~/Development/@adaptably/wp-foundation-theme/

      panes:
        - vim

  - theme:debug:
      root: ~/Development/@adaptably/wp-foundation-example/

      panes:
        - tail -f wp-content/debug.log

  - framework:
      root: ~/Development/@adaptably/wp-foundation-example/

      panes:
        - vim

  - plugins:
      root: ~/Development/@adaptably/wp-foundation-plugins/

      panes:
        - vim

  - library:build:
      root: ~/Development/@adaptably/wp-foundation-library/
      layout: 9b5f,118x34,0,0{74x34,0,0,18,43x34,75,0[43x25,75,0,19,43x8,75,26,20]}

      panes:
        - npm run storybook:dev
        - npm run styles:dev
        - npm run theme:dev
